{% set name = "vmap4fenics" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/BAMresearch/VMAP4Fenics

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =3.9
    - fenics =2019.1.0
    - numpy >=1.15.0
    - pyvmap
  run:
    - python =3.9
    - pyvmap
    - fenics =2019.1.0
    - numpy >=1.15.0
test:
  imports:

about:
  home: https://github.com/BAMresearch/VMAP4Fenics
  summary: 'VMAP Wrapper for Fenics FEM Simulations'
  license: MIT

extra:
  recipe-maintainers:
    - halbrech
