{% set name = "vmap4fenics" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  git_url: https://github.com/BAMresearch/VMAP4Fenics

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =3.9
    - fenics =2019.1.0
    - numpy >=1.15.0
    - pyvmap
  run:
    - python =3.9
    - pyvmap
    - fenics =2019.1.0
    - numpy >=1.15.0
test:
  imports:

about:
  home: https://github.com/BAMresearch/VMAP4Fenics
  summary: 'VMAP Wrapper for Fenics FEM Simulations'
  license: MIT
  description: |
    VMAP4Fenics is a wrapper that acts as a bridge between the Python interface 
    of VMAP and Finite Element Method (FEM) simulations conducted using Fenics. 
    The Wrapper extracts the geometry describing a Fenics problem from a Dolfin 
    Vector Function Space and stores the geometry among other information in an 
    HDF5 file. This Project is integrated in FenicsConrete and LeBeDigital 
    storing the results of concrete simulations conducted by 
    [BAM](https://www.bam.de/Navigation/EN/Home/home.html) (Bundesanstalt für 
    Materialforschung und -prüfung) the German Federal Institute for Materials 
    Research and Testing.

extra:
  recipe-maintainers:
    - halbrech
